name: test

on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Issue/PR number'
        required: true
      sha:
        description: 'Commit SHA'
        required: true

jobs:
  issue-normal-mode:
    runs-on: ubuntu-20.04
    name: Normal mode progress for issue comments
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: normal mode - create comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: normal-mode-comment
          message: 'normal mode - create comment'

      - name: Do some work
        run: echo "this step just prints this"

      - name: normal mode - update comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: normal-mode-comment
          message: 'normal mode - update comment'

  message-path:
    runs-on: ubuntu-20.04
    name: Use message-path to load message from file
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create MESSAGE.md
        run: echo "body from message-path" > MESSAGE.md
      - name: message path - create comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: message-path-comment
          message-path: ./MESSAGE.md

      - name: message path - missing input
        uses: ./
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: message-path-comment
          message-path: ./MISSING_INPUT.md

      - name: message path - both inputs provided, should fail
        uses: ./
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: message-path-comment
          message-path: ./MISSING_INPUT.md
          message: BOTH

  issue-append-mode:
    runs-on: ubuntu-20.04
    name: Append mode progress for issue comments
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: append mode - create comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: append-mode-comment
          message: "append mode - create comment"

      - name: Do some work
        run: echo "this step just prints this"

      - name: append mode - append comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: append-mode-comment
          append: true
          message: 'append mode - appended message to the create comment'

  issue-recreate-mode:
    runs-on: ubuntu-20.04
    name: Recreate mode progress for issue comments
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: recreate mode - create comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: recreate-mode-comment
          message: 'recreate mode - create comment'

      - name: Do some work
        run: echo "this step just prints this"

      - name: recreate mode - append comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: recreate-mode-comment
          recreate: true
          message: 'recreate mode - latest comment (should be posted after deleting the create comment)'

  commit-normal-mode:
    runs-on: ubuntu-20.04
    name: Normal mode progress for commit comments
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: normal mode - create comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          commit-sha: ${{ github.event.inputs.sha }}
          id: normal-mode-comment
          message: "normal mode - create comment"

      - name: Do some work
        run: echo "this step just prints this"

      - name: normal mode - update comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          commit-sha: ${{ github.event.inputs.sha }}
          id: normal-mode-comment
          message: 'normal mode - update comment'

  commit-append-mode:
    runs-on: ubuntu-20.04
    name: Append mode progress for commit comments
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: append mode - create comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          commit-sha: ${{ github.event.inputs.sha }}
          id: append-mode-comment
          message: 'append mode - create comment'

      - name: Do some work
        run: echo "this step just prints this"

      - name: append mode - append comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          commit-sha: ${{ github.event.inputs.sha }}
          id: append-mode-comment
          append: true
          message: 'append mode - appended message to the create comment'

  commit-recreate-mode:
    runs-on: ubuntu-20.04
    name: Recreate mode progress for commit comments
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: recreate mode - create comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          commit-sha: ${{ github.event.inputs.sha }}
          id: recreate-mode-comment
          message: 'recreate mode - create comment'

      - name: Do some work
        run: echo "this step just prints this"

      - name: recreate mode - append comment
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          commit-sha: ${{ github.event.inputs.sha }}
          id: recreate-mode-comment
          recreate: true
          message: 'recreate mode - latest comment (should be posted after deleting the create comment)'

  fail-mode-append-recreate:
    runs-on: ubuntu-20.04
    name: Fail when both append and recreate given
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Should error out and not comment anything
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: fail-mode-comment
          recreate: true
          append: true
          message: 'should error out as recreate and append mode could not be used together.'

  fail-mode-issue-commit-both:
    runs-on: ubuntu-20.04
    name: Fail when both number and sha given
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Error out
        uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          commit-sha: ${{ github.event.inputs.sha }}
          id: fail-mode-issue-commit-both
          message: 'should error out as both number and sha fields are given'

  fail-mode-issue-commit-none:
    runs-on: ubuntu-20.04
    name: Fail when both number and sha not given
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Error out
        uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          id: fail-mode-issue-commit-none
          message: 'should error out as both number and sha fields are not given'

  fail-comment:
    runs-on: ubuntu-20.04
    name: Fail comment progress
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Should comment and fail this job
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          number: ${{ github.event.inputs.number }}
          id: fail-comment
          fail: true
          message: ':x: This comment is to denote an error.'

